### ISSUE TITLE
[FEAT] Allow plugin installation from Docker

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon_enclosure#84]
### Objective

Currently, it doesn't appear there is any way to install plugins in a Docker image without rebuilding the image. Similar to [ovos-docker](https://github.com/OpenVoiceOS/ovos-docker/blob/dev/phal/Dockerfile), a mechanism to be able to install these plugins would make it easier to run Neon in a containerized environment (like Diana).

### Initial Implementation Requirements

- A way to install pip packages on container load, whether a new section in neon.yaml or a file somewhere on the filesystem

**Comment by NeonDaniel** [comment]
It looks like `ovos-docker` uses a `phal.list` file that is parsed as a list of Python requirements. I'm more inclined to put this in configuration but am open to either method.. One possibility that comes to mind:
```yaml
extra_dependencies:
  global: []
  audio: []
  speech: []
  skills: []
  messagebus: []
  enclosure: []
  admin: []
  gui: []
```
